<?php

?>
<div id="add_new_product" title="Add Product" class="actions-split" style="display: block;width: 100%;">
    <a href="<?= /* @noEscape */ $block->getUrl('csmarketplace/vproducts/new'); ?>" id="add_new_product_link" title="Add Product" class="action-default primary add" style="float: right;color: #fff !important;background: #000 !important;">
        <span><?= /* @noEscape */ __("Add Product");?></span>
    </a>
</div>
