<?php



?>
<?= $block->getChildHtml('info') ?>
<div class="order-details">
    <?= $block->getChildHtml('order_items') ?>
</div>
<script type="text/javascript">window.print();</script>
<style type="text/css">
    @media print {
        a[href]:after {
            content: none !important;
        },
        body{
            transform: scale(0.54);
            -webkit-transform: scale(0.54);
            -moz-transform: scale(0.54);
            -o-transform:  scale(0.54);
            -ms-transform:  scale(0.54);
        }
        @page {
            size: A4 portrait;
        }
    }

    .page-print .nav-toggle {
        display: none;
    }

    .page-wrapper {
        margin-left: 0px !important;
        width: 100%  !important;
</style>
