<?php


?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$vorder = $objectManager->create(\Magento\Framework\Registry::class)->registry('current_vorder');
$_order = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $block->getFullTaxInfo();
$taxHelper = $block->getData('taxHelper');
?>
<?php if ($vorder->getBaseTaxAmount()) { ?>
<tr>
    <td class="a-right" colspan="7">
        <div class="summary-collapse">
            <?php if ($taxHelper->displayFullSummary()): ?>
                <?= $block->escapeHtml(__('Total Tax')) ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('Tax')) ?>
            <?php endif;?>
        </div>
    </td>
    <td class="a-right last">
        <?= /* @noEscape */  $block->displayAmount($vorder->getPurchaseTaxAmount(), $vorder->getBaseTaxAmount()); ?>
    </td>
    <?php } ?>
</tr>
