<?php



// @codingStandardsIgnoreFile
?>

<script>
	require([
		"jquery",
		"jquery/jquery.cookie",
		"mage/mage",
		"mage/cookies"
	], function($){

	    $.extend($.mage.cookies.defaults, {
	        expires: null,
	        path: '<?= $block->getPath()?>',
	        domain: '<?= $block->getDomain()?>',
	        secure: false
	    });

	    $.extend($.cookie.defaults, $.mage.cookies.defaults);
	});
</script>
