<?php

?>

<div class="block ced-sociallogin-login">
    <div class="account-login">
        <?php if ($block->googleEnabled() || $block->facebookEnabled() || $block->twitterEnabled() || $block->linkedinEnabled()): ?>
            <h2><?= $block->escapeHtml("SocialLogin"); ?></h2>
        <?php endif; ?>

        <div class="ced-sociallogin-login-lower <?= $block->escapeHtml(implode(' ', $block->_getColSet())); ?>">
            <?php if ($block->googleEnabled()): ?>
                <div class="<?= $block->escapeHtml($block->_getButtCol()); ?> ced-sociallogin-login-lower-google">
                    <?= $block->getChildHtml('ced_google_login_button'); ?>
                </div>
            <?php endif; ?>
            <?php if ($block->facebookEnabled()): ?>
                <div class="<?= $block->escapeHtml($block->_getButtCol()); ?> ced-sociallogin-login-lower-facebook">
                    <?= $block->getChildHtml('ced_facebook_login_button'); ?>
                </div>
            <?php endif; ?>
            <?php if ($block->twitterEnabled()): ?>
                <div class="<?= $block->escapeHtml($block->_getButtCol()); ?> ced-sociallogin-login-lower-twitter">
                    <?= $block->getChildHtml('ced_twitter_login_button'); ?>
                </div>
            <?php endif; ?>
            <?php if ($block->linkedinEnabled()): ?>
                <div class="<?= $block->escapeHtml($block->_getButtCol()); ?> ced-sociallogin-login-lower-linkedin">
                    <?= $block->getChildHtml('ced_linkedin_login_button'); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
