<?php



?>
</div>
</div>
</div>
<div class="col-md-12 downloadable-information" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
		<?= /* @noEscape */ __('Downloadable Information') ?>
		</div>
		<div class="panel-body">
			<?= /* @noEscape */ $block->getChildHtml('sample');?>
			<br/>
			<?= /* @noEscape */ $block->getChildHtml('link');?>
		</div>
	</div>
</div>
