<?php ?> <?= /* @noEscape */ $block->getFormHtml() ?> <script>
    require(['jquery', "mage/mage"], function (jQuery) {

        jQuery('#<?= /* @noEscape */ $block->getFormId();?>').mage('form').mage('validation');

    });</script><script>
    window.onload = function () {
        var btn = document.getElementsByClassName('save-attribute-set');
        btn[0].onclick = function () {
            var textField = document.getElementById('attribute_set_name');
            var index1 = textField.className.indexOf("mage-error");
            var index2 = textField.className.indexOf("valid");
            if (index1 == -1 && index2 != -1) {
                document.getElementById("set-prop-form").submit();
            }
        };
    };</script>