<?php

?>
<?php /** @var \Ced\CsOrder\Block\Order\View\Totals $block */ ?>
<?php
$vorder = $block->getVorder();
$_order = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $block->getFullTaxInfo();
?>
<div class="order-totals">
    <table width="100%" cellspacing="0">
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Grand Total (Earned)') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getBaseOrderTotal(),
                        $vorder->getOrderTotal(),
                        false,
                        ''
                    ); ?>
                </strong>
            </td>
        </tr>
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Commission Fee') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getShopCommissionBaseFee(),
                        $vorder->getShopCommissionFee(),
                        false,
                        ' '
                    ); ?>
                </strong>
            </td>
        </tr>
        <tr>
            <td class="a-right" colspan="7">
                <div class="summary-collapse">
                    <strong>
                        <?= /* @noEscape */
                        __('Net Earned') ?>
                    </strong>
                </div>
            </td>
            <td class="a-right last">
                <strong>
                    <?= /* @noEscape */
                    $block->displayPrices(
                        $_order,
                        $vorder->getBaseOrderTotal() - $vorder->getShopCommissionBaseFee(),
                        $vorder->getOrderTotal() - $vorder->getShopCommissionFee(),
                        false,
                        ' '
                    ); ?>
                </strong>
            </td>
        </tr>
    </table>
</div>
