<?php



// @codingStandardsIgnoreFile
?>

<script>
require([
    "jquery",
    "jquery/ui"
], function($){

//<![CDATA[
    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?= $days['wide']?>,
            dayNamesMin: <?= $days['abbreviated']?>,
            monthNames: <?= $months['wide']?>,
            monthNamesShort: <?= $months['abbreviated']?>,
            infoTitle: "<?= __('About the calendar');?>",
            firstDay: <?= $firstDay?>,
            closeText: "<?= __('Close');?>",
            currentText: "<?= __('Go Today'); ?>",
            prevText: "<?= __('Previous');?>",
            nextText: "<?= __('Next');?>",
            weekHeader: "<?= __('WK'); ?>",
            timeText: "<?= __('Time');?>",
            hourText: "<?= __('Hour');?>",
            minuteText: "<?= __('Minute');?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showWeek: true,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false
        }
    });

    enUS = <?= $enUS?>; // en_US locale reference
//]]>

});
</script>
