<?php



// @codingStandardsIgnoreFile
?>

<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a style="font-size:24px;" class="navbar-brand panel-title" href="#"><?= __('Vendor')." ".__('Panel'); ?></a>
			</div>
			<?= $block->getChildHtml('top.links') ?>
			<?= $block->getChildHtml('sidebar') ?>
		</nav>
		<div id="loading-mask" style="display:none">
    		<p class="loader" id="loading_mask_loader"></p>
		</div>

