<?php

// @codingStandardsIgnoreFile
?>
<div class="row">
	<div class="col-md-12" style="margin-top:10px;">
		<div class="panel panel-default">
			<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
				<div  style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
					<?= __('Orders Report') ?>    
				</div>
			</div>
			<div class="panel-body">
				<?= $this->getChildHtml('orderReport2.list') ?>
				<div class="col-md-12" id="csmarketplace-vreports-vorders">
					<?= $this->getChildHtml('orderReport3.list') ?>
				</div>
			</div>
		 </div>
	</div>
</div>