<?php

?>
<?php
/** @var \Ced\CsOrder\Block\Order\Shipment\View\Items $block */
$vendorId = $block->getSession()->getVendorId();
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <thead>
        <tr class="headings">
            <th class="col-product"><span><?= /* @noEscape */
                    __('Product') ?></span></th>
            <th class="col-qty last"><span><?= /* @noEscape */
                    __('Qty Shipped') ?></span></th>
        </tr>
        </thead>
        <?php $_items = $block->getShipment()->getAllItems() ?>
        <?php $_i = 0;
        foreach ($_items as $_item): ?>
            <?php
            if ($_item->getOrderItem()->getVendorId() != $vendorId) {
                continue;
            } ?>

            <?php if ($_item->getOrderItem()->getParentItem()) {
                continue;
            } else {
                $_i++;
            } ?>
            <tbody class="<?= /* @noEscape */
            $_i % 2 ? 'odd' : 'even' ?>">
            <?= /* @noEscape */
            $block->getItemHtml($_item) ?>
            <?= /* @noEscape */
            $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
